//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAST
    {
        public int pid { get; set; }
        public int mid { get; set; }
        public string role_cast { get; set; }
    
        public virtual ACTOR ACTOR { get; set; }
        public virtual MOVIE MOVIE { get; set; }
    }
}
